# SPDX-FileCopyrightText: 2025 kdmg contributors <https://github.com/ForNeVeR/kdmg>
#
# SPDX-License-Identifier: Apache-2.0

[libraries]
dd-plist = "com.googlecode.plist:dd-plist:1.28"

[plugins]
gradle-jvm-wrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.2.0"
