# SPDX-FileCopyrightText: 2024-2025 kdmg contributors <https://github.com/ForNeVeR/kdmg>
#
# SPDX-License-Identifier: Apache-2.0

name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image:
          - macos-14
          - ubuntu-24.04
          - windows-2025
      fail-fast: false
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

  verify-encoding:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: Verify file encoding
        shell: pwsh
        run: |
          Install-Module VerifyEncoding -Repository PSGallery -RequiredVersion 2.2.0 -Force && Test-Encoding -ExcludeExtensions @('.bat')

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: REUSE compliance check
        uses: fsfe/reuse-action@v5
