name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  verify-encoding:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: Verify file encoding
        shell: pwsh
        run: |
          Install-Module VerifyEncoding -Repository PSGallery -RequiredVersion 2.2.0 -Force && Test-Encoding

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v4

      - name: REUSE compliance check
        uses: fsfe/reuse-action@v5
